mode: development # Use "hyde publish -c prod.yaml to have this automatically switch to production
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.
ignore:
    - panoimages
simple_copy:
    - media/zoomify/*
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.sorter.SorterPlugin
    - hyde.ext.plugins.less.LessCSSPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
    - hyde.ext.plugins.urls.UrlCleanerPlugin
context:
    data:
        site_title: Joe Beda's Photos
        author:
            name: Joe Beda
            url: "mailto:joe.site@bedafamily.com"
        google_analytics_id: UA-93698-4
        home_url: /index.html
        menu:
            - title: Photos
              url: /index.html
            - title: About
              url: /about.html
sorter:
    pano:
        attr: 
          - meta.created
        reverse: true
        filters:
            source_file.kind: html
            #is_processable: True
            #extends: panopage.j2
meta:
    author: Joe Beda
    description: Joe Beda
    
less:
  args:
    include-path: 'content/media/css/bootstrap'
urlcleaner:
  index_file_names:
    - index.html
